### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by Sarpedion** [ripjar/material-datetime-picker#95] opened 2016-12-04 00:04 UTC
When I install date picker (npm install material-datetime-picker --save),  and import it in js file 
`import MaterialDateTimePicker from 'material-datetime-picker';`
next error is thrown in browser console:

Uncaught SyntaxError: Unexpected token import
    at Object.<anonymous> (http://localhost:8080/app.js:2020:2)
    at __webpack_require__ (http://localhost:8080/app.js:554:30)
    at fn (http://localhost:8080/app.js:85:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:1720:2), <anonymous>:15:31)
    at Object.<anonymous> (http://localhost:8080/app.js:1720:2)
    at __webpack_require__ (http://localhost:8080/app.js:554:30)
    at fn (http://localhost:8080/app.js:85:20)
    at eval (eval at <anonymous> (http://localhost:8080/app.js:2122:2), <anonymous>:8:19)
    at Object.<anonymous> (http://localhost:8080/app.js:2122:2)
    at __webpack_require__ (http://localhost:8080/app.js:554:30)

What might be the cause of this issue?

**Comment by ncasich** [comment] 2016-12-28 17:14
Same issue
event-edit.js:1429 Uncaught SyntaxError: Unexpected token import

**Comment by jwhitfieldseed** [comment] 2017-01-16 22:42
Hi, thanks for the issue. It was caused by a problem in the way the module was bundled. It's fixed on master, and i'll cut a new NPM release in the next few days.

**Comment by jwhitfieldseed** [comment] 2017-01-16 22:42
Duplicate of #80

**Closed by jwhitfieldseed** 2017-01-16 22:42 UTC
