### ISSUE TITLE
When will we be able do select minutes?

### ISSUE THREAD

**Issue by jr69** [ripjar/material-datetime-picker#103] opened 2017-01-21 07:03 UTC
Hi, I am just wondering if we can select minutes with this

Maybe theres a branch or something I can pull?

**Comment by jwhitfieldseed** [comment] 2017-01-21 08:03
Duplicate of #72

**Closed by jwhitfieldseed** 2017-01-21 08:03 UTC

**Comment by jwhitfieldseed** [comment] 2017-01-21 08:05
I this believe fork has a branch for minutes: https://github.com/Pako7/material-datetime-picker

I've asked @Pako7 to open a PR. If that doesn't get opened, I'll add the feature soon.
